name: ai_object_tracker
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '^3.0.0'

dependencies:
  camera: ^0.10.5+5
  flutter:
    sdk: flutter
  tflite:
   git:
    url: https://github.com/Karma-234/flutter_tflite.git
    ref: fix
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/models/
